#!/bin/bash

ROOT_DIR=$(realpath $(dirname "$0"))
if [ ! -f ${ROOT_DIR}/config.env ]; then
    echo "Create a config file at ${ROOT_DIR}/config.env"
    echo "Starting config file found at ${ROOT_DIR}/config.env.example"
    exit 1
fi
source ${ROOT_DIR}/config.env

grep '^\[Peer\]' ${ROOT_DIR}/${wgifname}.conf | cut -d'#' -f2 | xargs | tr ' ' '\n'

