#!/bin/bash

ROOT_DIR=$(realpath $(dirname "$0"))
if [ ! -f ${ROOT_DIR}/config.env ]; then
    echo "Create a config file at ${ROOT_DIR}/config.env"
    echo "Starting config file found at ${ROOT_DIR}/config.env.example"
    exit 1
fi
source ${ROOT_DIR}/config.env

if [ ${EUID} -ne 0 ]; then
    echo "Run as root"
    exit 1
fi

set -e

cp ${ROOT_DIR}/${wgifname}.conf /etc/wireguard/${wgifname}.conf && \
    chown root:root /etc/wireguard/${wgifname}.conf && \
    chmod 600 /etc/wireguard/${wgifname}.conf

if [[ -n "$updatecommand" ]]; then
    ${updatecommand}
    echo "New ${wgifname}.conf installed and loaded"
else
    echo "New ${wgifname}.conf installed"
fi
